version: 2
updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "weekly"
        groups:
            -   name: "all"
                patterns:
                    - "*"